public static void main(String args[] ){
      
      String  binary="ravi";
      int l = binary.length();
      int temp=binary.indexOf(' '); //-1
      System.out.print(temp);
    //indexOf() return index of given character or string(first idex of first letter in case of string) otherwise return false;
    //counting will start with 0 example ,,binary.indexOf('a') ,, will return 1 index because in ravi .index for a is 1..
    }
